framework:
    messenger:
        transports:
             sync: 'sync://'
        routing:
             App\ExternalContent\Article\Application\Query\Article\FindRecentArticles\FindRecentArticlesQuery: sync
